# .github/workflows/ci.yml

name: Python CI # Just for Continuous Integration (testing) tets

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test: # Job just for testing
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: '3.11.1' # Match your runtime.txt

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # fetch-depth: 0 is not strictly needed if only testing

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Ensure pytest is in here

      - name: Run Pytests
        run: |
          pytest